### ISSUE TITLE
Upload custom loss layer?

### ISSUE THREAD

**Issue by nk-dev0** [yananweinbaa/RSRCNN#1]
Do you have any plans to upload the custom loss layer you mention in the paper? If not, do you have any tips for implementing from scratch?

**Comment by nkrall** [comment]
I see you've uploaded the loss layer cpp file, thanks! However, can you also upload the associated header file if necessary?

**Comment by xuyingxiao** [comment]
Does road structure based loss function mentioned in loss layer?
